---
deployment:
  tasks:
    - |
      for DEPLOYPATH in \
        /home2/aviatorj/public_html/
      do
        echo "Deploying to $DEPLOYPATH"
      
        /bin/cp -R aviatoradmin $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R css $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R dist $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R images $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R js $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R public $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R socket.io $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R unpkg.com $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R user $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R user $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R vendor $DEPLOYPATH >> $DEPLOYPATH/deploy.log
      
        /bin/cp .cpanel.yml $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp .htaccess $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp background.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp background1.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp background_bollywood.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp backgrounddimsound.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp cashout.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp cashout_2.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp default.php $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp favicon.ico $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp game-start.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp IMPORTANT $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp index.php $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp loading.gif $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp plane-crash.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp plane-crash.mp3.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp robots.txt $DEPLOYPATH >> $DEPLOYPATH/deploy.log
      
        /bin/cd laravel >> $DEPLOYPATH/deploy.log
        DEPLOYPATH=$DEPLOYPATH/laravel/
      
        /bin/cp -R app $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R bootstrap $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R config $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R database $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R fonts $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R lang $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R resources $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R routes $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R storage $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R tests $DEPLOYPATH >> $DEPLOYPATH/deploy.log


        /bin/cp artisan $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp composer.json $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp composer.lock $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp index.php $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp package.json $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp package-lock.json $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp vite.config.js $DEPLOYPATH >> $DEPLOYPATH/deploy.log
      
        /usr/local/bin/php /usr/local/bin/composer install --working-dir=$DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /usr/local/bin/php artisan migrate >> $DEPLOYPATH/deploy.log
      done
