---
deployment:
  tasks:
    - |
      for DEPLOYPATH in \
        /home2/aviatorj/public_html/
      do
        echo "Deploying to $DEPLOYPATH" >> $DEPLOYPATH/deploy.log
      
        /bin/cp -R aviatoradmin $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R css $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R dist $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R images $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R js $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R public $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R socket.io $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R unpkg.com $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R user $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R user $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp -R vendor $DEPLOYPATH >> $DEPLOYPATH/deploy.log
      
        /bin/cp .cpanel.yml $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp .htaccess $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp background.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp background1.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp background_bollywood.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp backgrounddimsound.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp cashout.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp cashout_2.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp default.php $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp favicon.ico $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp game-start.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp IMPORTANT $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp index.php $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp loading.gif $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp plane-crash.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp plane-crash.mp3.mp3 $DEPLOYPATH >> $DEPLOYPATH/deploy.log
        /bin/cp robots.txt $DEPLOYPATH >> $DEPLOYPATH/deploy.log
      
        /bin/cp -R laravel/app $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/bootstrap $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/config $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/database $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/fonts $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/lang $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/resources $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/routes $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/storage $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp -R laravel/tests $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log


        /bin/cp laravel/artisan $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp laravel/composer.json $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp laravel/composer.lock $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp laravel/index.php $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp laravel/package.json $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp laravel/package-lock.json $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /bin/cp laravel/vite.config.js $DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
      
        /usr/local/bin/php /usr/local/bin/composer install --working-dir=$DEPLOYPATH/laravel >> $DEPLOYPATH/deploy.log
        /usr/local/bin/php $DEPLOYPATH/laravel/artisan migrate --force >> $DEPLOYPATH/deploy.log
      done
